### ISSUE TITLE
Cannot infer a type for this parameter. Please specify it explicitly.

### ISSUE THREAD

**Issue by pulpoec** [Kristina-Simakova/photobooth_codelab_start_project#1]
Hello
New here

I have this error 

> currentMask.landmarkMap?.let { landmarks ->
the landmarks variable say: _Cannot infer a type for this parameter. Please specify it explicitly._
![image](https://user-images.githubusercontent.com/26312733/98875364-17c68c80-244a-11eb-96ea-decea319452f.png)

good job by the way!

**Comment by droid-girl** [comment]
I see by the highlighted places, it seems like you might have forgotten to define as  `val landmarkMap: ArrayList<FaceMaskElement>?` in FaceMask
