### ISSUE TITLE
preparing 3D models in blender

### ISSUE THREAD

**Issue by breathim** [Kristina-Simakova/photobooth_codelab_start_project#2]
I tried baking textures in blender of rabbit ears following your instruction in your blog . 
But when I try baking other 3d models from poly . It is not working fine . 
I tried https://poly.google.com/view/8wSCncR9jI7
https://poly.google.com/view/0Wsi-ygmiIX
The 3d model appears in the inverted form .

Also could you please share how to bake the texture using gltf .

**Comment by breathim** [comment]
I have solved this issue .

**Comment by droid-girl** [comment]
Hi, there is currently no support for gltf
